### ISSUE TITLE
Eq (20) in A is for Annihilation

### ISSUE THREAD

**Issue by hgothen** [AustenLamacraft/tqm-quarto#2]
Eq (20) in A is for Annihilation is with summation implied, right?

**Comment by AustenLamacraft** [comment]
Hi Henrik,

No I think it's right without summation. The point is that the matrix element is only nonzero when the product states in the bra and ket differ by the movement of one particle from $\beta$ to $\alpha$, and that picks out the term in the sum that will contribute.

**Comment by hgothen** [comment]
Thank you Austen for the quick reply!
I guess what you say is true if we only look at a single term of
```math
\hat A = \sum_{\alpha\beta}A_{\alpha\beta}a^\dagger_\alpha a_\beta
```
But since we are computing $\langle{\mathbf{N}}\rvert \hat A \lvert \mathbf{N'} \rangle$ it must be summed over $\alpha, \beta$. Can this be?

**Comment by hgothen** [comment]
> Thank you Austen for the quick reply! I guess what you say is true if we only look at a single term of
> A ^ = ∑ α β A α β a α † a β
> 
> But since we are computing ⟨ N | A ^ | N ′ ⟩ it must be summed over α , β . Can this be?

Forget about it, I think I got it now. You are right. Only one term can contribute
