### ISSUE TITLE
Fermi Gas just before eq. (2)

### ISSUE THREAD

**Issue by hgothen** [AustenLamacraft/tqm-quarto#4]
Maybe I am being a bit pedantic here, but I am a bit confused with this expression.

$`\langle{\mathbf{N}'}\rvert H_\text{int} \lvert \mathbf{N} \rangle = \frac{U_0}{V} \left(1-N_{\uparrow}(\mathbf{k}_1)\right)\left(1-N_{\downarrow}(\mathbf{k}_2)\right)N_{\downarrow}(\mathbf{k}_3)N_{\uparrow}(\mathbf{k}_4)`$

The left side is general, whereas the right side depends on specific $k_1, k_2, k_3, k_4$. So this does not quite check out. I think what is happening is that we are not looking at the matrix element with the full $H_\text{int}$ but just with one summand of $H_\text{int}$. That is how the $k_1, k_2, k_3, k_4$ come in. 

Hence my suggestion would be writing

$`\sum_{N'} \langle N' |a^\dagger_{\mathbf{k}_1,\uparrow}a^\dagger_{\mathbf{k}_2,\downarrow}a^{{\dagger}}_{\mathbf{k}_3,\downarrow}a^{{\dagger}}_{\mathbf{k}_4,\uparrow} |N\rangle =  \left(1-N_{\uparrow}(\mathbf{k}_1)\right)\left(1-N_{\downarrow}(\mathbf{k}_2)\right)N_{\downarrow}(\mathbf{k}_3)N_{\uparrow}(\mathbf{k}_4)`$

where the $|N\rangle$ is fixed and the sum over $N'$ makes sure we have a supply of bras from the left (one of which is going to match to produce a nonzero element)

Apologies for being so pedantic, but it is important for me to get it.

Cheers,
Henrik

**Comment by AustenLamacraft** [comment]
Ah, OK, I get your point. However, the values of $k_{1-4}$ are picked out by the occupation numbers that differ between $\mathbf{N}$ and $\mathbf{N}'$ (see the equation two above the Eq. (2)). So I would say that the LHS does contain those values...
